### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by suryaanshah** [ThatXliner/ThatXliner#2]
> ![image](https://user-images.githubusercontent.com/47082682/107775074-d81f8180-6d65-11eb-9b0e-d7df252c813d.png)

There is a typo in the selected word in [your README](https://github.com/ThatXliner/ThatXliner).
It should be *Software*.

**Comment by suryaanshah** [comment]
By the way, what does IMO mean in your ReadMe?

**Comment by ThatXliner** [comment]
Hi👋! I actually can't believe people actually read my profile. 

I'm very glad you caught that typo (mobile editing, y'know? 😅).

"IMO" means "In my opinion" (maybe I should add that in parenthesis)

**Comment by ThatXliner** [comment]
So it’s fixed! Thanks 😁 for helping me out!
